import LabShell, { GreenCluster, YellowCluster, type LabConfig } from './shared/LabShell'

const config: LabConfig = {
  number: 1,
  title: 'Unassigned Replicas',
  difficulty: 'Beginner',
  duration: '~5 min',
  description: 'Break a green cluster by enabling replicas on a single-node setup. Use the allocation explain API to diagnose exactly why the shard is unassigned, then fix it.',
  completionText: 'You broke a green cluster, used _cluster/allocation/explain to understand exactly why the shard couldn\'t be placed, and fixed it. This is the real incident workflow.',
  steps: [
    {
      id: 1,
      title: 'Verify the cluster is healthy',
      type: 'observe',
      visual: <GreenCluster />,
      what: 'Before breaking anything, confirm the cluster starts green. The airbnb-listings index has 0 replicas — all shards are assigned.',
      why: 'Establishing a known-good baseline is the first step of any incident response.',
      devMethod: 'GET', devPath: '/_cluster/health',
      apiMethod: 'GET', apiPath: '/api/cluster/health',
      insight: 'status: "green" means every primary and replica shard is assigned and active.',
      insightType: 'info',
    },
    {
      id: 2,
      title: 'Break it — enable 1 replica',
      type: 'action',
      what: 'Set number_of_replicas to 1 on airbnb-listings. OpenSearch will immediately try to place the new replica shard.',
      why: 'In a single-node cluster, the replica can never be assigned — it cannot co-locate with its own primary. This turns the cluster yellow.',
      devMethod: 'PUT', devPath: '/airbnb-listings/_settings',
      devBody: '{\n  "index": {\n    "number_of_replicas": 1\n  }\n}',
      apiMethod: 'PUT', apiPath: '/api/indices/airbnb-listings/replicas',
      apiBody: { count: 1 },
      insight: 'OpenSearch accepts the settings change immediately. The replica shard transitions to UNASSIGNED with reason INDEX_CREATED.',
      insightType: 'warning',
    },
    {
      id: 3,
      title: 'Observe yellow health',
      type: 'observe',
      visual: <YellowCluster />,
      what: 'Check cluster health again. The status is now yellow with 1 unassigned shard.',
      why: '"yellow" means all primary shards are active but at least one replica is not assigned. Data is safe, but the cluster has no redundancy.',
      devMethod: 'GET', devPath: '/_cluster/health',
      apiMethod: 'GET', apiPath: '/api/cluster/health',
      insight: 'unassigned_shards: 1 — the replica we just enabled. The primary (P0) is still STARTED and serving reads/writes.',
      insightType: 'warning',
    },
    {
      id: 4,
      title: 'Inspect shard state',
      type: 'observe',
      visual: <YellowCluster />,
      what: 'List the shards for airbnb-listings. You can see exactly which shard is unassigned and what node (if any) it is on.',
      why: 'The shard table is the most direct way to see where each shard lives. prirep=r means replica.',
      devMethod: 'GET', devPath: '/_cat/shards/airbnb-listings?v&h=index,shard,prirep,state,node',
      apiMethod: 'GET', apiPath: '/api/cluster/shards/airbnb-listings',
      insight: 'The primary (prirep=p) shows state=STARTED on node-1. The replica (prirep=r) shows state=UNASSIGNED with no node.',
      insightType: 'warning',
    },
    {
      id: 5,
      title: 'Diagnose with allocation explain',
      type: 'observe',
      visual: <YellowCluster />,
      what: 'This is the key API. It picks the first unassigned shard and explains exactly why it cannot be allocated — node by node.',
      why: 'In production this is always your first tool when a shard is stuck UNASSIGNED. It tells you whether the problem is disk watermark, rack awareness, or — as here — no eligible node.',
      devMethod: 'GET', devPath: '/_cluster/allocation/explain',
      apiMethod: 'GET', apiPath: '/api/cluster/allocation/explain',
      insight: '"can_allocate": "no" with reason "the shard cannot be allocated to the same node on which a copy already exists" — the single-node limitation in plain English.',
      insightType: 'warning',
    },
    {
      id: 6,
      title: 'Fix it — set replicas back to 0',
      type: 'fix',
      what: 'Drop the replica count back to 0. OpenSearch will immediately cancel the unassigned shard and the cluster recovers.',
      why: 'On a single-node dev cluster, replicas are always 0. In a multi-node cluster you would add more nodes instead of removing replicas.',
      devMethod: 'PUT', devPath: '/airbnb-listings/_settings',
      devBody: '{\n  "index": {\n    "number_of_replicas": 0\n  }\n}',
      apiMethod: 'PUT', apiPath: '/api/indices/airbnb-listings/replicas',
      apiBody: { count: 0 },
      insight: 'The cluster recovers in milliseconds — no data movement needed, the primary was never affected.',
      insightType: 'success',
    },
    {
      id: 7,
      title: 'Verify recovery',
      type: 'observe',
      visual: <GreenCluster />,
      what: 'Confirm the cluster is green again. Zero unassigned shards.',
      why: 'Always verify after a fix. In production you would also check _cat/shards to confirm specific shards are STARTED.',
      devMethod: 'GET', devPath: '/_cluster/health',
      apiMethod: 'GET', apiPath: '/api/cluster/health',
      insight: 'status: "green" — incident resolved. Running allocation explain now returns "All shards are assigned."',
      insightType: 'success',
    },
  ],
}

export default function UnassignedReplicasLab() {
  return <LabShell config={config} />
}
